apiVersion: v1
kind: Service
metadata:
  name: dtls-nodeport
spec:
  type: NodePort
  selector:
    app: dtls
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 5
  ports:
    - protocol: UDP
      port: 11111
      targetPort: 11111
